[package]
name = "wordfor-tauri"
version = "0.1.0"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
wordfor-core = { path = "../wordfor-core", default-features = false }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
